# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
 config.vm.box = "bento/ubuntu-20.04"
 config.vm.box_check_update = false

 config.vm.define "prod" do |prod|
        prod.vm.hostname = "prod"
        prod.vm.network "public_network", ip: "192.168.1.201"
#       server.vm.provision "shell", path: "provision-server.sh"
 end

 config.vm.define "dev" do |dev|
        dev.vm.hostname = "dev"
        dev.vm.network "public_network", ip: "192.168.1.200"
#       client.vm.provision "shell", path: "provision-client.sh"
 end

 config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
 end

end